[server]
mastodon_server = "https://mastodon.example.com" # Your Mastodon server URL
client_secret = "your_client_secret"             # Your Mastodon App client secret
access_token = "your_access_token"               # Your Mastodon App access token

[llm]
provider = "gemini"     # or "ollama"
ollama_model = "llama3"

[gemini]
api_key = "your_gemini_api_key" # Replace with your Gemini API key, if you don't have one, you can get it from https://aistudio.google.com/app/apikey
